#pragma once
#include <SDL2/SDL.h>
#include <map>

enum class CONTROLS {
  THRUST_FORWARD,
  THRUST_BACKWARD,
  TURN_CLOCKWISE,
  TURN_COUNTERCLOCKWISE,
  LAUNCH_TORPEDO
};

std::map<std::pair<int, CONTROLS>, SDL_Keycode> key_map = {
    {{0, CONTROLS::THRUST_FORWARD}, SDLK_UP},
    {{0, CONTROLS::THRUST_BACKWARD}, SDLK_DOWN},
    {{0, CONTROLS::TURN_CLOCKWISE}, SDLK_RIGHT},
    {{0, CONTROLS::TURN_COUNTERCLOCKWISE}, SDLK_LEFT},
    {{0, CONTROLS::LAUNCH_TORPEDO}, SDLK_MINUS},
    {{1, CONTROLS::THRUST_FORWARD}, SDLK_w},
    {{1, CONTROLS::THRUST_BACKWARD}, SDLK_s},
    {{1, CONTROLS::TURN_CLOCKWISE}, SDLK_d},
    {{1, CONTROLS::TURN_COUNTERCLOCKWISE}, SDLK_a},
    {{1, CONTROLS::LAUNCH_TORPEDO}, SDLK_TAB},
    {{2, CONTROLS::THRUST_FORWARD}, SDLK_z},
    {{2, CONTROLS::THRUST_BACKWARD}, SDLK_h},
    {{2, CONTROLS::TURN_CLOCKWISE}, SDLK_j},
    {{2, CONTROLS::TURN_COUNTERCLOCKWISE}, SDLK_g},
    {{2, CONTROLS::LAUNCH_TORPEDO}, SDLK_v}};
